matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      env: "iOS Swift 3.1"
      script:
        - set -o pipefail && xcodebuild -scheme Sourcing -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES | xcpretty
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: "iOS Swift 3.2/4.0"
      script:
        - set -o pipefail && xcodebuild -scheme Sourcing -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: "watchOS"
      script:
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination 'platform=watchOS Simulator,name=Apple Watch Series 2 - 38mm' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: "tvOS"
      script:
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination 'platform=watchOS Simulator,name=Apple Watch Series 2 - 38mm' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty